name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        # Updated from v2 to v4 for better performance and security
        uses: actions/checkout@v4

      - name: Set up Python
        # Updated from v2 to v5
        uses: actions/setup-python@v5
        with:
          # Changed from '3.13' to a stable, supported version
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train Model
        run: python model/train.py

      - name: Evaluate Model
        run: python model/evaluate.py

      - name: Run Unit Tests
        run: python -m unittest discover -s tests
